main: io.github.Andreaskal.testplugin.TestPlugin
name: TestPlugin
version: ${version}
author: Andreaskal
commands:
   basic:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>